spring:
  application:
    name: spring-boot-upgrade-agent
  ai:
    default-provider: ollama  # Custom property to define default
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: "https://models.github.ai/inference"
      chat:
        model: "openai/gpt-4.1"

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:14b
          temperature: 0.7
  main:
    banner-mode: off
logging:
  level:
    org.springframework: WARN
    root: WARN
llm:
  mode: external # can be 'external' or 'internal'
project:
  path: "/Users/Vishnu/REPOS/AIDEMO/ecommerce-auditlog"
