spring:
  application:
    name: spring-boot-upgrade-agent
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:14b
          temperature: 0.7
  main:
    banner-mode: off
logging:
  level:
    org.springframework: WARN
    root: WARN
